### ISSUE TITLE
[go-cs-bouncer] breaking change ahead

### ISSUE THREAD

**Issue by buixor** [hslatman/caddy-crowdsec-bouncer#13]
Hello,

A significant change was made in [go-cs-bouncer](https://github.com/crowdsecurity/go-cs-bouncer/pull/10) (commit : https://github.com/crowdsecurity/go-cs-bouncer/commit/5aef3b37e4fe6ba2e3b16432bde3f24b58d4a4d0)

the `.Run` method of go-cs-bouncer doesn't `Fatal` upon initialization failure (this failure would namely happen if the LAPI cannot be reached or cannot authenticate to LAPI).

The reason for this change is to allow bouncers/IPS to take advantage of `defer` statements for cleanup.

You can see reflected change in firewall-bouncer that uses this new version :
- https://github.com/crowdsecurity/cs-firewall-bouncer/pull/163

**Comment by hslatman** [comment]
Hi @buixor,

Thank you for the heads up. I should have a look at updating the dependency sometime 🙂 

As for the fatal errors: I already handled that more elegantly in this bouncer, since I'm not using the provided `Run`, but created my own based on the one provided by you. Errors are instead fed into a channel, so that the consumer of that error channel can decide what to do with the error. This bouncer can be configured to just log errors at error level, or fail hard(fatal, the old Go bouncer behavior) if it's desirable to do so. By default it'll only log at error level.
