### ISSUE TITLE
error: URL does not have a scheme

### ISSUE THREAD

**Issue by jonisapp** [hslatman/caddy-crowdsec-bouncer#32]
Hello, 
Same issue as previously here : https://github.com/hslatman/caddy-crowdsec-bouncer/issues/17

Deleting the entire Caddy configuration in order to resolve this problem does not seem to me to be a viable solution.
Would it be possible to have more information on the origin of this error?

The exact error log in caddy:
```json
{
  "level": "error",
  "ts": 1702530739.0322273,
  "logger": "admin.api",
  "msg": "request error",
  "error": "loading config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 5: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'crowdsec': provision http.handlers.crowdsec: getting crowdsec app: loading crowdsec app module: provision crowdsec: URL  does not have a scheme (i.e https)",
  "status_code": 400
}
```

**Comment by francislavoie** [comment]
FYI @hslatman the problem is here:

https://github.com/hslatman/caddy-crowdsec-bouncer/blob/87ada7fbe54ed44d2afdf1649bc62c52e71b9cc2/crowdsec/caddyfile.go#L15C2-L16C1

You can't set the `cfg` global option like this, that doesn't actually give the config to the Caddyfile adapter. For tools like Caddy Docker Proxy that might run the Caddyfile adapter separately from the Caddy runtime, this completely fails.

What you're supposed to do is return the config in this function (`return cfg, nil`) so that the Caddyfile adapter can actually set the App's config in the temporary config before adapting it to JSON.

See the `pki` app in Caddy's source for example: https://github.com/caddyserver/caddy/blob/387545a895ea71ae9f4f4e512dca136f92e45a74/caddyconfig/httpcaddyfile/pkiapp.go#L50

**Comment by hslatman** [comment]
@francislavoie thank you for the pointer! 

It took me a while to find a working method for doing this. 

After changing some of the `CrowdSec` initialization to get rid of the `cfg` I first had some errors. Then when diving into the details again I remembered having faced this issue before, and thus why I opted for that global `cfg` var. I'm not entirely sure, but at the time what I was doing with the `http` handler and `layer4` matcher depending on the global `crowdsec` seemed to be a bit of a special case, and at the time I couldn't find similar examples for. 

Following the approach in the `pkiapp` didn't cut it, but the `events` one did this, which seems to do what I'm after:

```golang
return httpcaddyfile.App{
	Name:  "crowdsec",
	Value: caddyconfig.JSON(cs, nil),
}, nil
```

Need to do a bit more cleanup and testing its behavior, but I think this is the right direction.

**Comment by francislavoie** [comment]
> It doesn't fully explain why it errors in this specific case

The issue is that a different process is used to adapt the config vs load the config. If it's not the same process, then `cfg` is not set when the JSON config is loaded so it breaks.

**Comment by hslatman** [comment]
With the [new release](https://github.com/hslatman/caddy-crowdsec-bouncer/releases/tag/v0.6.0) this should now be fixed. I've also added a fair amount of tests related to Caddyfile parsing, configuration loading and the general runtime of the bouncer to prevent future problems related to those. Thanks for reporting @jonisapp, and thanks for the help, @francislavoie 🙂

**Comment by francislavoie** [comment]
Looks much better, thanks!
