### ISSUE TITLE
How do we update the bouncer?

### ISSUE THREAD

**Issue by wdpronovost** [hslatman/caddy-crowdsec-bouncer#58]
Originally I setup the CrowdSec Caddy Bouncer via the `xcaddy` method because I could never get a download package from the Caddy site. 

Last week, I noticed that the bouncer had been updated so I went to see if I could get a custom caddy build with Cloudflare and CrowdSec, and was able to. 

I ended up stumbling upon a thread where someone else was having the same issue of how to install it as the documentation wasn't clear *to me*. [caddy](https://caddyserver.com/docs/build#package-support-files-for-custom-builds-for-debianubunturaspbian)

I was able to figure this out and I *think* I have it working correctly but when I review the CrowdSec dashboard in OPNSense it still shows the caddy bouncer is on v0.6.0.

Uncertain what I am supposed to do to get it to v0.7.1. I can see that I have the layer4 modules which were not present before.

**Comment by hslatman** [comment]
Hey @wdpronovost,

The `layer4` module was there before, if you installed it before, but there were some changes to support Caddyfile as the configuration format. There shouldn't be a change there, unless you now added the layer4 as a separate module too. It is optional, and only needed if you want TCP/UDP blocking in addition to blocking HTTP requests.

It sounds like you did build a custom Caddy manually. You can use the `list-modules` command to show module versions like this:

```
$ <your-caddy-binary> list-modules --versions
```

You should look for a line saying `crowdsec v0.7.1` (or the ones for HTTP/L4, which should have the same version, generally).

Alternatively, if you have Go installed locally, you can check the tagged version of the module using this command:

```
go version -m <your-caddy-binary> | grep -i github.com/hslatman/caddy-crowdsec-bouncer
```

It's possible that there's a mismatch between the version reported in your console vs. what's in the Go binary. It could be because of an error on my side of not having updated the version string in the binary, since it's not done automatically based on the module version. It's on my list of things to make it get the version automatically, and use that in the user agent for proper reporting.

**Comment by wdpronovost** [comment]
@hslatman thanks for the reply. List modules indicates v0.6.0 for the 2 entries. The `go version` command is returning "caddy: no such file or directory". Something is probably wrong on my side. It's ok (I hope)

**Comment by hslatman** [comment]
Ok, so that means you're still on `v0.6.0`. You can ignore the one with the Go command; it should return the same version.

If you used `xcaddy` to build Caddy, you should use something like this to get the `v0.7.1` version:

```
xcaddy build \
    --with github.com/hslatman/caddy-crowdsec-bouncer/crowdsec@v0.7.1
    --with github.com/hslatman/caddy-crowdsec-bouncer/http@v0.7.1
```

**Comment by wdpronovost** [comment]
@hslatman no, I didn't use xcaddy this time. That's what I was trying to highlight with the link. I was able to download a custom package with cloudflare and CrowdSec. I took that binary and followed the steps from that thread. I can try doing it again. I probably messed up.

**Comment by hslatman** [comment]
After downloading a custom binary from the Caddy website, which I think is what you tried, I got this:

```
caddy.listeners.layer4 v0.0.0-20231016112149-a362a1fbf652
crowdsec v0.7.1
http.handlers.crowdsec v0.7.1
layer4 v0.0.0-20231016112149-a362a1fbf652
layer4.matchers.crowdsec v0.7.1
layer4.matchers.ip v0.0.0-20231016112149-a362a1fbf652
layer4.matchers.local_ip v0.0.0-20231016112149-a362a1fbf652
```

So the custom builds there seem to work as expected.
